Repository SU-SWS/minimally_branded_subtheme, pull requests merged in 2022-03, with the labels that each got.

#10 Remove workmark stubbed
  dist/css/minimally_branded_subtheme.css
  dist/js/scripts.js
  minimally_branded_subtheme.info.yml
  src/js/minimally_branded_subtheme.behaviors.js
  src/scss/components/index.scss
  src/scss/components/local-footer/_local-footer.scss
  src/scss/components/local-footer/index.scss
  src/scss/components/main-nav/_main-nav.scss
  templates/block/block--system-branding-block.html.twig
  templates/components/local-footer/pattern-localfooter.html.twig
  templates/components/lockup/lockup.html.twig
Labels: size/s

#8 D8CORE-5563: adding a base link color of blue
  dist/css/minimally_branded_subtheme.css
  dist/js/scripts.js
  src/scss/base/_links.scss
  src/scss/base/index.scss
Labels: size/xs

#11 D8CORE-5582: fixing the color on responsive
  dist/css/minimally_branded_subtheme.css
  src/scss/components/main-nav/_main-nav.scss
Labels: size/xs

#12 Fixing the xs and sm mobile menus
  dist/css/minimally_branded_subtheme.css
  src/scss/components/main-nav/_main-nav.scss
Labels: size/xs

#13 1.0.0
  CHANGELOG.md
  README.md
  composer.json
  dist/assets/png/caret-down-digital-blue.png
  dist/assets/png/caret-up-digital-blue.png
  dist/assets/png/search-digital-blue.png
  dist/assets/svg/caret-down-digital-blue.svg
  dist/assets/svg/caret-up-digital-blue.svg
  dist/assets/svg/search-digital-blue.svg
  dist/css/minimally_branded_subtheme.css
  dist/css/stanford_starter.css
  dist/js/scripts.js
  minimally_branded_subtheme.info.yml
  minimally_branded_subtheme.libraries.yml
  minimally_branded_subtheme.theme
  package-lock.json
  package.json
  src/assets/png/caret-down-digital-blue.png
  src/assets/png/caret-up-digital-blue.png
  src/assets/png/search-digital-blue.png
  src/assets/svg/caret-down-digital-blue.svg
  src/assets/svg/caret-up-digital-blue.svg
  src/assets/svg/search-digital-blue.svg
  src/js/minimally_branded_subtheme.behaviors.js
  src/js/scripts.js
  src/scss/base/_links.scss
  src/scss/base/index.scss
  src/scss/components/brandbar/_brandbar.scss
  src/scss/components/brandbar/index.scss
  src/scss/components/index.scss
  src/scss/components/lockup/_lockup.scss
  src/scss/components/lockup/index.scss
  src/scss/components/main-nav/_main-nav.scss
  src/scss/components/main-nav/index.scss
  src/scss/components/masthead/_masthead.scss
  src/scss/components/masthead/index.scss
  src/scss/components/search/_search.scss
  src/scss/components/search/index.scss
  src/scss/components/secondary-nav/_secondary-nav.scss
  src/scss/components/secondary-nav/index.scss
  src/scss/theme/_link.scss
  stanford_starter.theme
  templates/block/block--system-branding-block.html.twig
  templates/components/brand-bar/brand-bar.html.twig
  templates/components/global-footer/global-footer.html.twig
  templates/components/local-footer/pattern-localfooter.html.twig
  templates/components/lockup/lockup.html.twig
  templates/page.html.twig
  webpack.config.js
Labels: size/xl

#15 1.0.1
  CHANGELOG.md
  minimally_branded_subtheme.info.yml
Labels: patch
